// <auto-generated />
using System;
using Exchange_App.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exchange_App.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exchange_App.DAL.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyName")
                        .IsRequired();

                    b.Property<double>("PurchasePrice");

                    b.Property<double>("SellingPrice");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Exchange_App.DAL.Entities.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountClientCurrency");

                    b.Property<double>("AmountTargetCurrency");

                    b.Property<string>("Cashier")
                        .IsRequired();

                    b.Property<int?>("ClientCurrencyId");

                    b.Property<int?>("ClientId");

                    b.Property<int?>("TargetCurrencyId");

                    b.HasKey("Id");

                    b.HasIndex("ClientCurrencyId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TargetCurrencyId");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("Exchange_App.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountCurrencyUsedToday");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Exchange_App.DAL.Entities.Exchange", b =>
                {
                    b.HasOne("Exchange_App.DAL.Entities.Currency", "ClientCurrency")
                        .WithMany()
                        .HasForeignKey("ClientCurrencyId");

                    b.HasOne("Exchange_App.DAL.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Exchange_App.DAL.Entities.Currency", "TargetCurrency")
                        .WithMany()
                        .HasForeignKey("TargetCurrencyId");
                });
#pragma warning restore 612, 618
        }
    }
}
